### ISSUE TITLE
How to make him answer only based on the content of my document when asking

### ISSUE THREAD

**Issue by xiaojun2sheng** [jerryjliu/llama_index#1099]
How to make him answer only based on the content of my document when asking, and don't use knowledge beyond the document to reply to me. If you can't find the corresponding answer in the document, reply to my fixed copy

**Comment by Smyja** [comment]
> How to make him answer only based on the content of my document when asking, and don't use knowledge beyond the document to reply to me. If you can't find the corresponding answer in the document, reply to my fixed copy
You can do something like this.
```
response = index.query(
    "how do i connect cockroachdb?",
    optimizer=SentenceEmbeddingOptimizer(percentile_cutoff=0.5),
    service_context=service_context,
    response_mode="compact",
    similarity_cutoff=0.8
)

#if the output of response is None print sorry i dont know
if str(response) == "None":
    print("Hmm, I don't know enough")
else:
    print(response)

```

**Comment by xiaojun2sheng** [comment]
@Smyja Solved my problem, thank you

**Comment by bfalchuk** [comment]
Hi, where do we find detailed information about how response_mode works . I see here:
[https://github.com/jerryjliu/llama_index/blob/main/gpt_index/indices/response/builder.py#L30](https://github.com/jerryjliu/llama_index/blob/main/gpt_index/indices/response/builder.py#L30)
that there are 4 modes: default, compact, tree, no-text. 
Do any of these modes correspond to make Llama-gpt behave like @xiaojun2sheng wanted? That is, to answer *only* from the trained document-set and the supplied context, rather than from OpenAI's knowledge of the world? Is there a "dial to turn" that sets how much of the answer comes from the context vs the open-world?
