### ISSUE TITLE
Prompt asking for a list returns 1 random item

### ISSUE THREAD

**Issue by dano1066** [jerryjliu/llama_index#1130]
I have a super basic script that I want to use for querying an index. 

`print("Enter prompt")
prompt = input()

index = GPTSimpleVectorIndex.load_from_disk('testIndex.json')
print(index.query(prompt))`

I am asking it to give me 10 key points from the document and it responds with a valid point that is indeed from the index but only one. It seems to give me back a single item. It might be something like 

> INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 4794 tokens
> INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 9 tokens
> 
> 6. some valid and important fact...etc.

Since the data is returned is valid data and its exactly what I wanted, I know its definitely querying the indexc but it has me wondering if i am not outputting this correctly.

**Comment by Disiok** [comment]
Hey, this might be because simple vector index retrieves the top 1 most relevant document chunk by default. You can try to change similarity_top_k parameter, or consider using another index that's better suited for summarization tasks. Read more at https://gpt-index.readthedocs.io/en/latest/use_cases/queries.html#summarization

**Comment by hongyishi** [comment]
Over what size of text are you searching for the points? Also if you give the specific prompt it might help since it might take some prompt engineering.
