### ISSUE TITLE
[AWS Lambda] Allow arbitrary directory for downloads with download_loader

### ISSUE THREAD

**Issue by bkamapantula** [jerryjliu/llama_index#1185]
I'm using llama-index as one of the dependencies in AWS Lambda but receive an error: `OSError: [Errno 30] Read-only file system`

I tried setting the path to `/tmp` in the file where the logic is invoked but that’s not doing anything. Wikipedia reader code:

```py
WikipediaReader = download_loader("WikipediaReader")
```

```bash
OSError: [Errno 30] Read-only file system: '/var/task/llama_index/readers/llamahub_modules/library.json'
```

It'll be good to have an argument to pass an arbitrary download directory.

**Comment by tranquanghuy0801** [comment]
Thanks for raising this issue and adding a PR to fix this. I think the PR also fixed the issue I had.

In case someone looks at it here later, I have a similar issue with `download_loader("PDFReader")` when deploying using AWS Lambda. The solution to fix the issue is adding `custom_path` parameter like below as in Lambda filesystem, only `/tmp` directory is writable:
```
PDFReader = download_loader("PDFReader", custom_path="/tmp/llamahub_modules")
```
