### ISSUE TITLE
Answer from outside the documents

### ISSUE THREAD

**Issue by humtumiit** [jerryjliu/llama_index#1321]
We have been using Simple vector index to create indexing of our custom documents but when we ask general questions like What is AI, Where is United States of America?  and so on. This returns the answers even if uploaded document has no context of such information. 

It looks like it it getting information from documents and retaining its existing information in pre trained model. 

Is there any way to overcome , control this challenge? I want this to restrict only to my uploaded document.

**Comment by kindler-king** [comment]
Same @humtumiit , I have been wondering how to do this too. One thing I have noticed is giving the prompt to restrict it to the document set sometimes works, but many a times its unpredictable if it's going to generate response or assemble it from our custom document set.

**Comment by humtumiit** [comment]
Thanks Kindler-king. I am struggling with this and not able to figure it out. Which Indexing are you using for this? 
Any idea, are you facing this challenge in anyone of specific indexing or all indexes ?

**Comment by yasergsi** [comment]
I think this is a required and important feature that changes that enforces LLM behavior to restrict answering out-of-context questions/queries. There should be some configuration that allows us to do this.

**Comment by humtumiit** [comment]
Thanmks you [yasergsi](https://github.com/yasergsi)

**Comment by logan-markewich** [comment]
@yasergsi @humtumiit this is mostly a prompt engineering problem, not as easy as flicking a switch. Especially since OpenAI is constantly updating their models, it can be hard to keep prompts working perfectly.

See here for how to customize the main query prompt templates - the text_qa_template and the refine_template
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules
