### ISSUE TITLE
The baseGPTIndex delete function is not complete because it needs to remove from docstore.ref_doc_info

### ISSUE THREAD

**Issue by joiemoie** [jerryjliu/llama_index#1345]
index.delete() is missing this call:

index.docstore.ref_doc_info.pop(key)

This needs to happen somehow before it is properly deleted. Otherwise, during refresh, the doc isn't recognized as actually deleted.

**Comment by logan-markewich** [comment]
@joiemoie This should be fixed, or at least much clearer, see this page for detailed guide/usage! Docs are not deleted from the docstore by default (since multiple indexes can be sharing the same docstore), but you can set a flag to force the delete

https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/document_management.html
