### ISSUE TITLE
What is the interpretation of num_output in PromptHelper()?

### ISSUE THREAD

**Issue by maspotts** [jerryjliu/llama_index#2409]
I can't figure out what num_output controls in the call to PromptHelper(): is there an obvious correspondence to the LLM configuration or behaviour?  eg. is it a measure of the number of tokens the LLM can predict?  (Seems unlikely). Hoping it's easy to understand :)

Thanks!

**Comment by sid8491** [comment]
Total number of tokens used for output generation, if it is too less and response if big, the response from the LLM is cut-off mid way.

> I can't figure out what num_output controls in the call to PromptHelper(): is there an obvious correspondence to the LLM configuration or behaviour? eg. is it a measure of the number of tokens the LLM can predict? (Seems unlikely). Hoping it's easy to understand :)
> 
> Thanks!

**Comment by maspotts** [comment]
Thanks!  So I'm thinking that the parameterization should work like this: given max_tokens (eg. = 8192 for GPT-4), I define a max_input_length and max_output_length such that:

  max_input_length + max_output_length <= max_tokens

and then specify:

  prompt_helper = PromptHelper(max_input_size = max_input_length, num_output = max_output_length, ...)
  llm = ChatOpenAI(max_tokens = max_tokens, ...)

So (eg) I might have for GPT-4:

  prompt_helper = PromptHelper(max_input_size = 7000, num_output = 1192, ...)
  llm = ChatOpenAI(max_tokens = 8192, ...)

Is that right?

**Comment by logan-markewich** [comment]
@maspotts that is incorrect

max_tokens is the number of output tokens.

max_intput_size is the max context window of the LLM

num_output is how many tokens llama-index leaves available to generate (normally, this should be the same as max_tokesn)

Since LLMs generate one token at a time, add it to the input, and generate the next, llama-index needs to leave `num_output` tokens of room to generate an answer.
