### ISSUE TITLE
Persit GPTSQLStructStoreIndex

### ISSUE THREAD

**Issue by unitedsoftworks** [jerryjliu/llama_index#2504]
When trying to run `load_index_from_storage` on a persisted GPTSQLStructStoreIndex index, i am given an error `ValueError: sql_database must be specified`
The code below is what im using. is there some secret to persisting this? 

The docs dont really cover it and they just give examples of it during runtime, but the problem is the create_engine, SQLDatabase, and GPTSQLStructStoreIndex calls are all way too slow to be used in a real time chat bot so i was trying to save the index to disc for it to remember the schema and then load it back later, which is much faster

```
def save_file(self):
        from sqlalchemy import create_engine
        engine = create_engine(self.connection_string) #slow
        sql_database = SQLDatabase(engine) #slow
        index = GPTSQLStructStoreIndex([], sql_database=sql_database, ) #slow
        index.storage_context.persist(self.index_file_path)

def load_file(self):
        storage_context = StorageContext.from_defaults(persist_dir=self.index_file_path)
        index = load_index_from_storage(storage_context=storage_context)
        self._index_file = index
```

**Comment by ccueto36** [comment]
I second this. Having the same issue.

**Comment by krish240574** [comment]
I found that the persist() methods stores empty jsons inside the index_file_path - vectorstore.json, index_store.json and docstore.json, all empty, just the following :
vector_store.json  - {"embedding_dict": {}, "text_id_to_doc_id": {}}
index_store.json - {"index_store/data": {"<SOME ID>": {"__type__": "sql", "__data__": {"index_id": "<SOME ID>", "summary": null, "context_dict": {}}}}
docstore: {} - which I would expect, since I'm creating the GPTSQLStructStoreIndex with documents as []. 
I suspect the culprit is the index_store which is empty.

**Comment by Disiok** [comment]
You'd need to pass in `sql_database` when loading like 
```python
index = load_index_from_storage(storage_context=storage_context, sql_database=sql_database)
```

Overall, would recommend just re-creating the index instead of save/load.
