### ISSUE TITLE
Optimize the query time for retrieval engine

### ISSUE THREAD

**Issue by balasurajp** [jerryjliu/llama_index#3193]
<img width="1025" alt="image" src="https://github.com/jerryjliu/llama_index/assets/34001536/055a706f-e663-4239-a412-01543de0bbe8">

please replace the cosine similarity query retrieval with the dot product from sklearn or numpy which will speed up the query time by multifold.

**Comment by Disiok** [comment]
Absolutely, time to make this performant!

**Comment by logan-markewich** [comment]
@balasurajp we are already using numpy for cosine similarity. It's quite fast in my benchmarks. I tried adding batch calculations but this actually slows things down when you have a lot of nodes (likely due to memory allocation?)

Going to close this for now, but here's some current benchmarks

![image](https://github.com/jerryjliu/llama_index/assets/22285038/9fd3797b-d854-4c84-812e-0f0aa1d29d8d)
