### ISSUE TITLE
Newer versions throw error "TypeError: 'method' object is not iterable" on query_engine.query()

### ISSUE THREAD

**Issue by rajphaniraj** [jerryjliu/llama_index#3374]
I'm using a custom LLM with code based on
https://github.com/amrrs/LLM-QA-Bot/blob/main/LLM_Q%26A_with_Open_Source_Hugging_Face_Models.ipynb

With older versions of llama_index and langchain  (0.5.27 and  0.0.142) the code works correctly, as in the line
response = index.query( "What's the cost of Whisper model?")  in cell 13

With newer versions of llama_index and langchain (0.6.7 and  0.0.169), and the code changed to use the newer syntax

query_engine = index.as_query_engine(service_context=service_context)
response = query_engine.query( "What's the cost of Whisper model?") 

I get the error TypeError: 'method' object is not iterable, on line 145 of RetrieverQueryEngine, which is listed below

response = self._response_synthesizer.synthesize(
    query_bundle=query_bundle,
    nodes=nodes,)

**Comment by Disiok** [comment]
Could you show more of you code to help us debug?

**Comment by rajphaniraj** [comment]
[minimal_example.zip](https://github.com/jerryjliu/llama_index/files/11481441/minimal_example.zip)

Here's a minimal example ; the cmd file ( Windows) installs specific versions of llama_index and langchain, and runs the exact same code ( minimal.py) with each pair of versions. The 2 txt files are the output ; the 0.6.7.txt has the full exception stacktrace, while the 0.5.27.txt has the correct answer from the query

The code does have an if statement based on the version of llama_index, since the query syntax is slightly different between the 2 versions, as shown below.

if ( llama_index.__version__ == '0.6.7'):

    query_engine = index.as_query_engine(service_context=service_context)
    response = query_engine.query( "What benchmarks was the model validated on?") 
else:
    response = index.query( "What benchmarks was the model validated on?")

**Comment by adityakadrekar16** [comment]
I am getting the exact same error.

**Comment by Disiok** [comment]
@logan-markewich  any idea what's going on here? Do you think it's related to using custom LLM?

**Comment by chaklam-silpasuwanchai** [comment]
I got the same problem with 

torch       : 1.13.0
langchain   : 0.0.170
transformers: 4.21.3
llama_index : 0.6.7

**Comment by logan-markewich** [comment]
@Disiok @chaklam-silpasuwanchai @adityakadrekar16 @rajphaniraj 

Looks like newer versions of langchain have changed how to declare custom LLMs. Please see this page (notice the property decorator on identifying params):

https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html

I can update the docs with this new syntax as well

**Comment by rajphaniraj** [comment]
@logan-markewich  Thanks, that does work. The langchain documentation does indicate that _identifying_params is optional, but it seems to be needed for this use case.  This is what I had to add to my CustomLLM class to make it work.

    from typing import Mapping
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {"n": "nothing important"}

**Comment by chaklam-silpasuwanchai** [comment]
@logan-markewich @rajphaniraj  thanks, it works.

This is how I write my custom LLM....not sure it is correct but it works.  Copy right from Langchain website.

`from typing import Mapping, Optional, Any, List
from langchain.callbacks.manager import CallbackManagerForLLMRun

class CustomLLM(LLM):
    
    n: int
    model_name = "google/flan-t5-large"
    pipeline = pipeline("text2text-generation", model=model_name, device=1, model_kwargs={"torch_dtype":torch.bfloat16})
        
    @property
    def _llm_type(self) -> str:
        return "custom"
    
    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
    ) -> str:
        if stop is not None:
            raise ValueError("stop kwargs are not permitted.")
        
        out = self.pipeline(prompt, max_length=9999)[0]["generated_text"]
        return out[:self.n]
    
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {"n": self.n}`

Version: 
torch       : 1.13.0
langchain   : 0.0.171
transformers: 4.21.3
llama_index : 0.6.7

**Comment by FatimaHabib** [comment]
I still have the same error message 

TypeError: 'method' object is not iterable

llama_index 0.6.7
torch 1.13.0+cu117
langchain 0.0.171
transformers 4.21.3
`


 class customLLM(LLM):

    model_name = "google/flan-t5-large"
    # Transformer Pipelines
    pipeline = pipeline("text2text-generation", model=model_name, device=0, model_kwargs={"torch_dtype":torch.bfloat16}) 
    @property
    def _llm_type(self) -> str:
        return "custom"
    
    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
    ) -> str:
        if stop is not None:
            raise ValueError("stop kwargs are not permitted.")
        
        out = self.pipeline(prompt, max_length=9999)[0]["generated_text"]
        return out[:self.n]
    
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {"n": self.n}
    def _call(self, prompt, stop=None):
        return self.pipeline(prompt, max_length=9999)[0]["generated_text"]
 
    def _identifying_params(self):
        return {"name_of_model": self.model_name}

    def _llm_type(self):
        return "custom"

# Imported from llama-index
llm_predictor = LLMPredictor(llm=customLLM()) 
`

**Comment by logan-markewich** [comment]
I'm going to close this issue as fixed 👍 the docs have the correct links and examples 

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced

**Comment by rajivmehtaflex** [comment]
Above link is no longer working,Can you give me proper information,Because I'm stuck with the same issue till now.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in ()
      1 query_engine = index.as_query_engine()
----> 2 response = query_engine.query("What this document talk about?")
      3 print(response)

/usr/local/lib/python3.10/dist-packages/llama_index/indices/query/base.py in query(self, str_or_query_bundle)
     21             if isinstance(str_or_query_bundle, str):
     22                 str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23             response = self._query(str_or_query_bundle)
     24             return response
     25 

/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/retriever_query_engine.py in _query(self, query_bundle)
    173                 )
    174 
--> 175             response = self._response_synthesizer.synthesize(
    176                 query=query_bundle,
    177                 nodes=nodes,

/usr/local/lib/python3.10/dist-packages/llama_index/response_synthesizers/base.py in synthesize(self, query, nodes, additional_source_nodes)
    123             CBEventType.SYNTHESIZE, payload={EventPayload.QUERY_STR: query.query_str}
    124         ) as event:
--> 125             response_str = self.get_response(
    126                 query_str=query.query_str,
    127                 text_chunks=[

/usr/local/lib/python3.10/dist-packages/llama_index/response_synthesizers/compact_and_refine.py in get_response(self, query_str, text_chunks, **response_kwargs)
     32         # the refine template does not account for size of previous answer.
     33         new_texts = self._make_compact_text_chunks(query_str, text_chunks)
---> 34         response = super().get_response(
     35             query_str=query_str, text_chunks=new_texts, **response_kwargs
     36         )

/usr/local/lib/python3.10/dist-packages/llama_index/response_synthesizers/refine.py in get_response(self, query_str, text_chunks, **response_kwargs)
     47                 # if this is the first chunk, and text chunk already
     48                 # is an answer, then return it
---> 49                 response = self._give_response_single(
     50                     query_str,
     51                     text_chunk,

/usr/local/lib/python3.10/dist-packages/llama_index/response_synthesizers/refine.py in _give_response_single(self, query_str, text_chunk, **response_kwargs)
     78         for cur_text_chunk in text_chunks:
     79             if response is None and not self._streaming:
---> 80                 response = self._service_context.llm_predictor.predict(
     81                     text_qa_template,
     82                     context_str=cur_text_chunk,

/usr/local/lib/python3.10/dist-packages/llama_index/llm_predictor/base.py in predict(self, prompt, **prompt_args)
    114             else:
    115                 formatted_prompt = prompt.format(llm=self._llm, **prompt_args)
--> 116                 response = self._llm.complete(formatted_prompt)
    117                 output = response.text
    118 

/usr/local/lib/python3.10/dist-packages/llama_index/llms/langchain.py in complete(self, prompt, **kwargs)
     44 
     45     def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
---> 46         output_str = self._llm.predict(prompt, **kwargs)
     47         return CompletionResponse(text=output_str)
     48 

/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py in predict(self, text, stop, **kwargs)
    824         else:
    825             _stop = list(stop)
--> 826         return self(text, stop=_stop, **kwargs)
    827 
    828     def predict_messages(

/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py in __call__(self, prompt, stop, callbacks, tags, metadata, **kwargs)
    784             )
    785         return (
--> 786             self.generate(
    787                 [prompt],
    788                 stop=stop,

/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py in generate(self, prompts, stop, callbacks, tags, metadata, **kwargs)
    556             ] * len(prompts)
    557 
--> 558         params = self.dict()
    559         params["stop"] = stop
    560         options = {"stop": stop}

/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py in dict(self, **kwargs)
    882     def dict(self, **kwargs: Any) -> Dict:
    883         """Return a dictionary of the LLM."""
--> 884         starter_dict = dict(self._identifying_params)
    885         starter_dict["_type"] = self._llm_type
    886         return starter_dict

TypeError: 'method' object is not iterable

**Comment by logan-markewich** [comment]
@rajivmehtaflex https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced
