### ISSUE TITLE
Request for Document Weighting Feature in gpt-index

### ISSUE THREAD

**Issue by marcmagn1** [jerryjliu/llama_index#340]
Can different weights be assigned to multiple documents used as embeddings when querying a large language model through gpt-index library?

When working with a corpus consisting of multiple documents, prioritizing certain documents over others in the event of multiple index query matches can be useful.

Is this feature currently available or can it be added in the future?

Thanks for your time.

**Comment by pgoldweic** [comment]
I was going to suggest a similar enhancement but at the index level. That is, given is a set of distinct (list, tree or similar) indices over sets of documents, I'd like to give more weight to one (or more) of these indices over the others because, for example, this index is constructed over 'local' documents vs. external ones, and so its contents should override any content present in the other, less relevant, indices).
