### ISSUE TITLE
using llama index to query/inference a LLM using GPU

### ISSUE THREAD

**Issue by suraj-gade** [jerryjliu/llama_index#3779]
Hi,

I am building a chatbot using LLM like fastchat-t5-3b-v1.0  and want to reduce my inference time. 

Below is the code that I am using to do inference on Fastchat LLM. 
```
from llama_index import GPTListIndex, SimpleDirectoryReader, GPTVectorStoreIndex, PromptHelper, LLMPredictor
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LangchainEmbedding, ServiceContext
from transformers import T5Tokenizer, T5ForConditionalGeneration

model_name = 'lmsys/fastchat-t5-3b-v1.0'
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

from transformers import pipeline

pipe = pipeline(
    "text2text-generation", model=model, tokenizer=tokenizer,
    max_length=1024, temperature=0, top_p = 1,no_repeat_ngram_size=4, early_stopping=True
)

from langchain.llms import HuggingFacePipeline
llm = HuggingFacePipeline(pipeline=pipe)

embed_model = LangchainEmbedding(HuggingFaceEmbeddings())

# set maximum input size
max_input_size = 2048
# set number of output tokens
num_outputs = 512
# set maximum chunk overlap
max_chunk_overlap = 20
# set chunk size limit
chunk_size_limit = 512
prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap)

service_context = ServiceContext.from_defaults(embed_model=embed_model, llm_predictor=LLMPredictor(llm), prompt_helper=prompt_helper, chunk_size_limit=chunk_size_limit)

# build index
documents = SimpleDirectoryReader('data').load_data()

new_index = GPTListIndex.from_documents(documents, service_context=service_context)

# query with embed_model specified
query_engine = new_index.as_query_engine(
    retriever_mode="embedding", 
    verbose=True,
    #streaming=True,
    similarity_top_k=1
    #service_context=service_context
)

response = query_engine.query("sample query question?")
```
Here the "data" folder has my full input text in pdf format, and am using the llama_index and langchain pipeline to build the index on that and fetch the relevant chunk to generate the prompt with context and query the FastChat model as shown in the code.

This takes around 2 mins on average to get a response for a query. I want to bring down this inference time.

is there any way to introduce GPU for the inference with llama_index and langchain/huggingface pipeline steps above? Also if there is any way to optimize these steps to get better response time?
Please let me know your thoughts on this.

**Comment by LLCF** [comment]
I have the same question

**Comment by ethdig** [comment]
Hello!

I understand that you want to reduce the inference time for your chatbot using LLama, specifically the FastChat model. To speed up the processing and achieve better response times, here are some suggestions:

GPU Usage: To increase processing speed, you can leverage GPU usage. The Hugging Face Transformers library supports GPU acceleration. You may need to use a deep learning framework like PyTorch or TensorFlow with GPU support to run your model on a GPU.

For example, to enable GPU usage with PyTorch:

python
Copy code
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
This will run your model on a CUDA-enabled GPU.

Data Size Reduction: To improve processing speed, you can reduce the size of the data used. For instance, you can experiment with smaller values for parameters like "max_input_size," "num_outputs," "max_chunk_overlap," and "chunk_size_limit." These parameters limit the input size, output length, and chunk size.

Parallel Processing: Consider parallel processing strategies that can handle multiple queries simultaneously. You can use libraries like "concurrent.futures" or "multiprocessing" in Python to process queries in parallel. This way, you can obtain the outputs faster.

Caching: Cache frequently used queries to reduce response times. Caching stores the results of recurring queries, enabling faster responses.

Model Optimization: Explore techniques to optimize your model by reducing memory usage and computational costs. For example, you can compress your model to a smaller size or research memory-efficient solutions.

These suggestions serve as starting points to reduce inference time and achieve faster responses. However, since I don't have detailed information about the specific dependencies and libraries you mentioned, I recommend exploring customized solutions tailored to your specific context.

**Comment by logan-markewich** [comment]
just need to set the device or device_map on the pipeline there. Feel free to read more on the hugging face docs!

**Comment by BennisonDevadoss** [comment]
does it use multi GPU or is does it only uses the single GPU

**Comment by logan-markewich** [comment]
Just a single. If you want multi gpu, use a framework like text generation interface or vllm
