### ISSUE TITLE
GPTVectorStoreIndex.from_documents stuck and slow

### ISSUE THREAD

**Issue by shravanv90** [jerryjliu/llama_index#3929]
I am trying to index the documents `GPTVectorStoreIndex.from_documents(documents)`  using the github connector. It's a pretty small repo but The indexing seems stuck. Is there anyway to get the progress with logs? is there something else to check?

**Comment by allendred** [comment]
After my test, more than 5 articles will get stuck

**Comment by csrss** [comment]
Same here. Its stuck with a very small amount of data.

**Comment by naffenuf** [comment]
Got it to work with 11 documents.  2100 hangs forever.  Using OpenAI embedding I see no account activity.  I've gotten embeddings for larger data sets to work with llama_index but that was with the old GPTSimpleVectorIndex, not the renamed GPTVectorStoreIndex.  Any clues appreciated.

**Comment by logan-markewich** [comment]
Is this still an issue for people? Not sure what the problem is but we do have an option to show progress now. Additionally for large datasets, you can try increasing the batch size

https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/index/usage_pattern.html#high-level-api

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/embeddings/usage_pattern.html#batch-size

Feel free to re-open or reach out on our discord!
