### ISSUE TITLE
Add Redis as a supported vector database

### ISSUE THREAD

**Issue by tylerhutcherson** [jerryjliu/llama_index#452]
Redis now allows for Vector storage, retrieval, similarity search, and hybrid querying/fitlering with the [RediSearch](https://redis.io/docs/stack/search/) module. It's rich developer ecosystem, low-latency, high-availability capabilities make this a good choice for dev teams looking to build LLM apps using a database they likely already have in their stack :)

This is something my team could help with.

**Comment by jerryjliu** [comment]
@tylerhutcherson would love your help on this! At the very least we could add a RedisReader into LlamaHub https://github.com/emptycrown/llama-hub/tree/main/loader_hub - so that users can load data from Redis given some initial query string/vector/filters; they can then load this data into a GPT Index data structure.

Afterwards we can brainstorm how to design a vector store index backed by Redis (the vector store index will handle the text chunking of documents, storage, and integration with other indices). similar to what we have for pinecone, qdrant, weaviate, etc.

**Comment by anzemur** [comment]
Hi @jerryjliu, the project looks great. I am just wondering if there are there any benefits to using the gpt_index library over just a vector database with a similarity search?

**Comment by jerryjliu** [comment]
@tylerhutcherson just checking, is this still something you+your team would be able to help with? no rush. our recent vector store refactors should allow it to be easier to add a new vector store index

**Comment by tylerhutcherson** [comment]
@jerryjliu Absolutely. We've been doing some planning/organizing on our end. @Spartee has also started thinking about this.

**Comment by Spartee** [comment]
@jerryjliu march is a busy month. But this is something we have community members and customers asking about so it's a priority. 

I have a start that with a little more work I could open as a draft PR to get feedback if your interested. 

Really great work btw.
