### ISSUE TITLE
indices base refresh_ref_docs not working as expected

### ISSUE THREAD

**Issue by hawktang** [jerryjliu/llama_index#5772]
version 0.16.19

same refresh_ref_docs could not be recognized as the same.

From the the debug the hash of original file can not be found.

existing_doc_hash always return none and all file was insert again

**Comment by hawktang** [comment]
when refresh, each document would have new doc_id, therefore no hash value will be get at all by doc_id

**Comment by logan-markewich** [comment]
For refresh to work, you'll need to explicitly set the doc id of each document when constructing the original index

Then when refreshing, the same document should have the same doc id. This way, the new and old documents can be matched using doc_id, and their contents will determine if they are refreshed.

If the doc_id of one of the new documents is not already in the index, it will be inserted (which is why explicitly setting the doc_id is important)

**Comment by logan-markewich** [comment]
This page has a very minimal example of everything

https://gpt-index.readthedocs.io/en/latest/how_to/index_structs/document_management.html

**Comment by hawktang** [comment]
Thank you so much for your work in llama index and your fast reply.

I am SimpleDirectoryReader and from_documents, so the doc_id are not assigned manually.

I am thinking using doc_store and index_structure to recover the documents with former ID to make it fully automatically.

If it is working my I raise a PR for this to contribute llama index

**Comment by logan-markewich** [comment]
If it works yea, definitely make a pr 👍

When using a reader, you can still go through the documents and set the doc_id manually as well.

**Comment by logan-markewich** [comment]
Hmm, I think using extra_info for this is not a great solution, especially since the extra_info is inherited by a documents nodes, and the LLM reads the extra_info field

Although I'm confused about the original issue here. As long as doc_id is set to something consistent (i.e. the same source document should always have the same doc_id)

This could be a lot easier if SimpleDirectoryReader had the option to set the doc_id to something reliable (like the filename). Just made a PR for this as well actually https://github.com/jerryjliu/llama_index/pull/6055

**Comment by hawktang** [comment]
Thank you so much for help.

I think problem will be solved by the PR https://github.com/jerryjliu/llama_index/pull/6055

In my solution I am basically using the ref_doc_hash as doc_id the merged PR.

**Comment by ernkoch** [comment]
Issue remains for me
`for doc in docs:
            logger.debug(doc.doc_id)
refreshed_docs = chroma_index.refresh(docs)
logger.info(refreshed_docs)`

results in this output for me and also everything is getting refreshed, despite docs and there context not changing:
Output
`Initialized ChromaVectorStore.
id_1
id_2
id_3
id_4
[True, True, True, True]`
So the ids are fixed and still refresh happens everywhere. 
Have tried using ref_docs but none of this works. Also I cannot refresh based on nodes.

Thankful for any ideas (using llama_index 8.56)
