### ISSUE TITLE
[Question]: Is it possible to insert documents one by one into a ComposableGraph?

### ISSUE THREAD

**Issue by YasmineMh** [jerryjliu/llama_index#6111]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it possible to insert documents one by one into a ComposableGraph?

**Comment by logan-markewich** [comment]
Not quite. Since a graph is made up of several sub-indexes, each of those sub-indexes usually contains a specific subset of documents.

You'd have to pick which sub-index to insert into ahead of time.

Although auto-inserting is an interesting idea to explore 🤔

**Comment by logan-markewich** [comment]
You'd have to re-create the graph in order to add a new sub-index 🤔 If this is the approach you want to take, I would save each index individually and then build the graph at runtime.

Definitely, the operations around the graph could be better supported 🙂

Going to close this issue since I think we were also chatting on discord. Feel free to reach out anytime over there!

**Comment by YasmineMh** [comment]
yeah sure, thank you!
