### ISSUE TITLE
[Feature Request]: Please stop the frequent and unnecessary renaming of important classes (GPTSimpleVectorIndex, GPTVectorStoreIndex, VectorStoreIndex, etc.)

### ISSUE THREAD

**Issue by xjdeng** [jerryjliu/llama_index#6117]
### Feature Description

Can you please decide on a single name and just stick to it?  It breaks our code every time it's renamed and it seems to be happening every few updates!

### Reason

I don't foresee any issues with LlamaIndex sticking with the same class names and not constantly renaming them.  Having to rewrite our code every time there's an update in order to accomodate important classes being renamed at the whim of the devs is not a practical solution, esp if it leaves important systems that rely on llamaindex in a state of limbo

### Value of Feature

So we don't need to rename important classes in our code in order to get it to continue working whenever there's an update to Llamaindex

**Comment by logan-markewich** [comment]
Apologies for the extra work! It is unfortunate, but the renaming was mostly necessary.

GPTVectorStoreIndex -> VectorStoreIndex
Note that all old imports should still be working. Here, we remove the GPT prefix, mainly because we are not tied to GPT

GPTSimpleVectorIndex -> GPTVectorStoreIndex
Here, we consolidated all vector index (simple, chroma, pinecone, etc.) into a single class. Easier to maintain and develop with.

One suggestion is that production code (or code you rely on) should have the version pinned, so that when dependencies update your code doesn't instantly break and you have time to nicely manage updates👍🏻

**Comment by ranjanj1** [comment]
Lol, I was thinking GPTVectorStoreIndex is NOT same as VectorStoreIndex
