### ISSUE TITLE
[Feature Request]: CustomLLM should be able to handle streaming

### ISSUE THREAD

**Issue by Thytu** [jerryjliu/llama_index#6316]
### Feature Description

similar to https://github.com/jerryjliu/llama_index/issues/3142 but for [custom LLM](https://github.com/jerryjliu/llama_index/blob/main/docs/how_to/customization/custom_llms.md#example-using-a-custom-llm-model---advanced).

**Comment by logan-markewich** [comment]
Since the custom LLM is an extension of a langchain class, supporting streaming is quite difficult

langchain uses a callback system for streaming, rather than giving a user the raw generator. Because of this, in your customLLM, you'll have to implement one of their callback handlers that uses the `on_llm_new_token()` to get the streamed output

If you are using a huggingface model though, I highly recommend using our huggingface predictor, as it natively supports our streaming: https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-huggingface-llm

**Comment by logan-markewich** [comment]
With recent changes, a custom LLM just has to implement 2 method (or optionally 4 if you want streaming)
- chat
- stream_chat
- complete
- stream_complete

https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced

Class to extend:
https://github.com/jerryjliu/llama_index/blob/main/llama_index/llms/custom.py
