### ISSUE TITLE
[Question]: Has anyone tried KnowledgeGraphDemo on local LLM?

### ISSUE THREAD

**Issue by karrtikiyer** [jerryjliu/llama_index#6539]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to reproduce [this](https://github.com/jerryjliu/llama_index/blob/5fcdbfc429ee08193ce03e57bcb61e3a827fa72a/docs/examples/index_structs/knowledge_graph/KnowledgeGraphDemo.ipynb) example on local LLM, however with Open LLAMA 13B or GPT 4 All Snoozy it does not give the desired results.
Wanted to know if we can expect this to work local LLM's?

**Comment by karrtikiyer** [comment]
I even tried with Vicuna Wizard 13B `wizard-vicuna-13B.ggmlv3.q6_K.bin` which seems to be one of better performing Local LLM's. Any suggestion or advise on how we can make this work on Local LLM's?

**Comment by logan-markewich** [comment]
OpenSource LLMs are not that great yet tbh

The hardest part here will be getting the LLM to extract triplets properly. You can tune the prompt for this by setting it here:
`index = KnowledgeGraphIndex.from_documents(...., kg_triple_extract_template=my_kg_template)`

And here is the default prompt:
https://github.com/jerryjliu/llama_index/blob/5fcdbfc429ee08193ce03e57bcb61e3a827fa72a/llama_index/prompts/default_prompts.py#L255

**Comment by karrtikiyer** [comment]
Thanks @logan-markewich , I skipped the triplet extraction and manually added all the triplets (as tuples using `index.upsert_triplet`) just to check the querying part. However even the querying part seems to be a challenge, do you have any thoughts around why querying part would be difficult or a challenge with local LLM's?

**Comment by logan-markewich** [comment]
So the query can be difficult for two reasons

1. we use the LLM to extract keywords from the query text
2. if enough nodes/triplets are retrieved so that there is too much text for a single LLM call, llama-index refines the answer across multiple LLM calls. Open-Source LLMs are generally bad at doing this right now (the prompt is a little complex)

You can adjust the prompt for both 1 and 2

```
index.as_query_engine(refine_template=MY_REFINE_TEMPLATE, query_keyword_extract_template=MY_KEYWORD_TEMPLATE)
```

Here's the default keyword template
https://github.com/jerryjliu/llama_index/blob/5fcdbfc429ee08193ce03e57bcb61e3a827fa72a/llama_index/prompts/default_prompts.py#L130

Here's the default refine template
https://github.com/jerryjliu/llama_index/blob/5fcdbfc429ee08193ce03e57bcb61e3a827fa72a/llama_index/prompts/default_prompts.py#L81

**Comment by logan-markewich** [comment]
Going to close for now. Feel free to reach out on discord!
