### ISSUE TITLE
[Question]: newbie question

### ISSUE THREAD

**Issue by g3434343** [jerryjliu/llama_index#6556]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I need to know if I use a LLM like open-assistant or any other. Will it analyze my docs using more than the token limit? Usually they're 512 or 2048, no?
Please answer this question. I know to use LLM but I don't know how this would perform.

**Comment by logan-markewich** [comment]
You will have to set the context window limit according to the LLM you use, otherwise it will likely use the default of 4096 and cause some problems

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model-advanced

https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-huggingface-llm
