### ISSUE TITLE
[Question]: When I used colab, the query didn't answer

### ISSUE THREAD

**Issue by HopeZhi** [jerryjliu/llama_index#6765]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

halo，editors.
When I used colab, the query didn't answer,just like this  
![image](https://github.com/jerryjliu/llama_index/assets/137783782/ba8f9f72-790c-49a1-8bc8-c131067dcfc9)
![image](https://github.com/jerryjliu/llama_index/assets/137783782/f5be762e-eef5-4940-975b-1d923ad59e1d)

**Comment by logan-markewich** [comment]
Did the documents actually go into the index?

Try `print(documents)` before constructing the index. You might have the incorrect path to the file

**Comment by rjarun8** [comment]
> 

Pls, correct the document's argument. Since it is a file, use the input argument input_files to send the document in

from llama_index import VectorStoreIndex,SimpleDirectoryReader
**_documents = SimpleDirectoryReader(input_files = ["test2.txt"]).load_data()_**
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
query_engine.query("what is my name?")

**Comment by jon-chuang** [comment]
It should honestly give an error if it is not a list

**Comment by HopeZhi** [comment]
Thanks！guys，i have solved this error，XD
