### ISSUE TITLE
Llama Index To Avoid Hallucination - Possible for Llama Index to only query our knowledge corpus?

### ISSUE THREAD

**Issue by ks233ever** [jerryjliu/llama_index#7008]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it possible for Llama Index to only provide a response if it's contained within our knowledge corpus?

E.g., following this[ tutorial](https://towardsdatascience.com/how-i-built-a-custom-gpt-based-chatbot-in-under-10-minutes-with-llamaindex-2102f0173420), it appears llama index used to return a message, _It is not possible to answer this query given the context information provided,_  if the query was irrelevant to the knowledge corpus we trained it on. This is what we would like to happen. However it seems now it will answer all questions, using a combo of the provided data and its own knowledge.

**Comment by logan-markewich** [comment]
Yea, it seems like the default prompts have drifted a bit, due to updates from openai. I can try and take a look at updating these at some point.

Still in my testing, there are many questions the LLM will refuse to answer. GPT-3.5 is especially cautious. 

In the meantime, feel free to customize the templates
https://gpt-index.readthedocs.io/en/latest/core_modules/model_modules/prompts.html#modules
