### ISSUE TITLE
[Question]: Is it posible to give an agent an index as engine without using the query engine tool?

### ISSUE THREAD

**Issue by DomenicoMireles** [jerryjliu/llama_index#7384]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I chose an agent as retirver over a chat engine given the extended capabilities but one diference is that when using chat engine, you can ask questions about the index like if it would be part of its training dateset, while with an agent, in order to get the right answer, you must specify that it gotta use the query engine tool.

This isnt ideal when you want the agent to always consider the index before making an aswer.

Is there another way to give an agent access to an index other than as a tool?

**Comment by logan-markewich** [comment]
Not sure If I understand the question fully, but here's a few comments.

Agents use query engine tools because the tool that is used is based on the description of that tool. So the agent looks at the chat history and the list of tools/descriptions, and decides if a tool should be invoked. In the latest version of llama-index, you can force at least one tool to always be called by using `agent.chat("...", function_call=<tool_name>"`

Using something like the context chat engine, which is based on a retriever, it will always retrieve text from your index, and use that text, along with the chat history, to answer the user message. This is best controlled by setting an appropriated `system_prompt` when creating the chat engine.

**Comment by logan-markewich** [comment]
Perfect!
