### ISSUE TITLE
[Bug]: context_template is not passed through in ContextChatEngine.from_defaults()

### ISSUE THREAD

**Issue by gregory-shklover** [jerryjliu/llama_index#7456]
### Bug Description

ContextChatEngine.from_defaults() does not pass "kwargs" to the constructor.
Example: passing context_template=... is ignored

### Version

0.8.11.post3

### Steps to Reproduce

create an index.
call index.as_chat_engine(mode="context", context_template="...")

"context_template" argument is not propagated in ContextChatEngine.from_defaults()

**Comment by logan-markewich** [comment]
Yea the kwargs are more there since we abuse kwargs in a few places, so it avoids errors if extra things are passed in that are not used (I know, terrible practice lol)

Well make a PR to add this as a config. Just a heads up that the only requirement for the context template is that it contains a `{context_str}` f-string variable

**Comment by logan-markewich** [comment]
Should be inluded in the next pypi release, thanks for flagging

**Comment by gregory-shklover** [comment]
Thanks for quick fix!
