### ISSUE TITLE
[Question]:  max_top_k in VectorIndexAutoRetriever is not working and its setting to default 2?

### ISSUE THREAD

**Issue by apthagowda97** [jerryjliu/llama_index#7518]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

From the [API Reference ](https://gpt-index.readthedocs.io/en/latest/api_reference/query/retrievers/vector_store.html) documentation I can see the `max_top_k` parameter which can be set to control the top k doc to fetch.

It internally takes the min of the `query_spec.top_k` and `max_top_k` as shown below.

```
if query_spec.top_k is None:
    similarity_top_k = DEFAULT_SIMILARITY_TOP_K
else:
    similarity_top_k = min(query_spec.top_k, self._max_top_k)
```

As I am not setting the `query_spec.top_k` its setting to the default value of 2. 
How can I set the `query_spec.top_k` ?

**Comment by apthagowda97** [comment]
Ok, this is strange. 
If I didn't set the `query_spec.top_k` by writing `set top k to 10` in query. It always set to 2 (by default). 
Then there is no use of `max_top_k`.

Should it be changed to max instead of min in the below code or another parameter called `similarity_top_k` to override the default 2?
`similarity_top_k = min(query_spec.top_k, self._max_top_k)`

Let me know which approach is correct, I'll open a PR.

**Comment by logan-markewich** [comment]
@apthagowda97 You are using the auto retriever right?

**Comment by apthagowda97** [comment]
Yes I am using auto retriever.

**Comment by logan-markewich** [comment]
@apthagowda97 the LLM is supposed to set the top k, but it seems like it may be failing to do so properly

So then, it gets set to the default.

You can likely make a PR to add a user-configurable fallback rather than the default in the constructor

The user default would just need to be added here I think
https://github.com/jerryjliu/llama_index/blob/1dffadee72addff5c66b6739909c06081b2673c2/llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py#L98

**Comment by logan-markewich** [comment]
I can also try adding this later if you don't have time
