### ISSUE TITLE
[Bug]: langchain.embeddings.base not found

### ISSUE THREAD

**Issue by wingsuiting** [jerryjliu/llama_index#7713]
### Bug Description

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-32-2911fa256dd2>](https://localhost:8080/#) in <cell line: 2>()
      1 get_ipython().system('pip install llama-index')
----> 2 import llama_index

4 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/bridge/langchain.py](https://localhost:8080/#) in <module>
     18 
     19 # embeddings
---> 20 from langchain.embeddings.base import Embeddings
     21 from langchain.embeddings import HuggingFaceBgeEmbeddings, HuggingFaceEmbeddings
     22 

ModuleNotFoundError: No module named 'langchain.embeddings.base'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Version

0.8.29

### Steps to Reproduce

Ran the following code in a Google colab instance:

!pip install llama-index
import llama_index

**Comment by divjad---** [comment]
Do you perhaps also get an error when using the LLM from hugging-face and calling `create_llama_chat_agent`? I just downgraded langchain from 0.0.293 to 0.0.292 because of the error in this issue. Could the problem be related to the langchain version? The error is:
`ValidationError: 1 validation error for LLMChain
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)`

**Comment by logan-markewich** [comment]
@divjad--- that utility is completely un-maintained at the moment. Tbh I would like to totally remove it at some point. If you have a fix for it please feel free to submit a PR though

We have our own agent classes/tools that are quite flexible and easier to use
https://gpt-index.readthedocs.io/en/latest/core_modules/agent_modules/agents/modules.html
