### ISSUE TITLE
[Question]:  Consistently getting rate limit error when building index

### ISSUE THREAD

**Issue by sagardashora** [jerryjliu/llama_index#7879]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using the basic code to index a single text document with about 10 lines

```
from llama_index import VectorStoreIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
```

I have the free tier openAI account which still should be sufficient for a small document. HOwever, I am consistently getting rate limit error when building index.
Saw the other threads regarding this but none have a conclusive answer.
I am using latest library version

**Comment by KrishnaPayyavula** [comment]
@dosu-bot

Nothing mentioned in the above worked for me.

I use Enterprise Azure Open AI Account.

Below are version of openai, llama-index and langchain.

```
openai==0.28.1
langsmith==0.0.60
llama-index==0.8.62
```

I get below error 
`openai.error.RateLimitError: Requests to the Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms. Operation under Azure OpenAI API version 2023-05-15 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 9 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.`

**Comment by ryanhalliday** [comment]
I think this is due to being on the free tier which is limited to 3 requests per minute to `text-embedding-ada-002`

I fixed this by adding $10 to my OpenAI API account to push into the next Usage Tier: https://platform.openai.com/docs/guides/rate-limits/usage-tiers

They have a help article on this here: https://help.openai.com/en/articles/6843909-rate-limits-and-429-too-many-requests-errors

Also note that I had to wait ~5 minutes for the API to recognise my change in tier. 

Ideally llama-index should have a rate limit that follows the [rate limit headers](https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers) that OpenAI returns, but also you will need money in your OpenAI account sooner rather than later anyway...

**Comment by SKashyap1999** [comment]
https://docs.llamaindex.ai/en/stable/getting_started/customization.html
I have used a chromadb collection with a sentence transformer embedding model as my embedding function. 
I have used this collection in my ChromaVectorStore which is acting as the storage context to the vector index.

Why am I getting a rate-limit error from openai, when I explicitly used the sentence transformers model(multi-qa-MiniLM-L6-cos-v1) for my embeddings?

**Comment by ryanhalliday** [comment]
@SKashyap1999 Are you sure you passed in the service context etc? https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html

Post code or it's impossible to help

**Comment by nise** [comment]
That's how it works for me:
```
from llama_index.core import Document
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)

# ...
index = VectorStoreIndex.from_documents(documents)
```

**Comment by cyril23** [comment]
When using GoogleGenAIEmbedding instead of OpenAIEmbedding the following settings fixed my `429 RESOURCE_EXHAUSTED` errors (see https://docs.llamaindex.ai/en/stable/api_reference/embeddings/google_genai/):
```python
embed_model_name = "gemini-embedding-exp-03-07" # other models may have different quotas
embed_model = GoogleGenAIEmbedding(
	model_name=embed_model_name,
	api_key="YOUR_API_KEY",
	embed_batch_size=1, # Defaults to 100. 101+: "BatchEmbedContentsRequest.requests: at most 100 requests can be in one batch"
	retry_min_seconds=31, # (float): Minimum wait time between retries. Defaults to 1.
	retry_max_seconds=32, # (float): Maximum wait time between retries. Defaults to 10.
	#retries=3, # (int): Maximum number of retries for API calls. Defaults to 3.
	#retry_exponential_base=2 # (float): Base for exponential backoff calculation. Defaults to 2.
	#timeout=10 # (int): Timeout for API calls in seconds. Defaults to 10.
)
```
This resulted in ~0.9 documents/second being added to my Chroma collection. You can probably tweak it higher and it still works, or try to rise the Google quotas.

For OpenAIEmbedding I don't know though.



> That's how it works for me:
> 
> ```
> Settings.embed_model = HuggingFaceEmbedding(
>     model_name="BAAI/bge-small-en-v1.5"
> ```

What https://github.com/run-llama/llama_index/issues/7879#issuecomment-2311714449 suggested of course works too because when you do the embeddings locally you don't get rate limited by yourself..
